version: '3'
services:
  myapp-main:
    image: qap2_docker_container:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/search_engine_db
      #- spring.datasource.url=jdbc:mysql://search_engine_db.ce2vcezehro2.us-east-1.rds.amazonaws.com/search_engine_db
      - spring.datasource.password=class1234
      - spring.datasource.username=admin
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
